version: "3"
services:
  docs:
    build: .
    volumes:
      - ./user-guide/docs:/code/docs
      - ./user-guide/mkdocs.yml:/code/mkdocs.yml
    ports:
      - 127.0.0.1:8000:8000
    command: mkdocs serve --dev-addr 0.0.0.0:8000 --watch-theme --config-file /code/mkdocs.yml
    container_name: ds_docs
