INHERIT: ./mkdocs.base.yml

site_name: DesignSafe User Guide
site_description: DesignSafe User Guide
site_url: https://designsafe-ci.org/user-guide/
# NOTE: Unrecognized by MkDocs, but recognized by ReadTheDocs theme
site_favicon: https://www.designsafe-ci.org/favicon.ico

theme:
    name: readthedocs
    logo: img/NSF_NHERI-DS.svg
    cms_url: https://designsafe-ci.org/ # TACC Feature
    cms_name: designsafe-ci.org # TACC Feature
    nav_name: User Guide # TACC Feature
    navigation_depth: 4
    features:
      - navigation.top
    nav_redirects: # TACC Feature
      - before: '#data-depotcuration-office-hours'
        after: https://www.designsafe-ci.org/facilities/virtual-office-hours/
    analytics:
      gtag: G-D96RT1T24K

extra_css:
  # TACC/TACC-Docs:/mkdocs.base.yml
  - css/core/bootstrap.css
  - css/core/core-styles.css
  - css/core/tacc-docs.css
  # DesignSafe/DS-User-Guide
  - css/ds-docs.css

plugins:
  - search
  - include-markdown

nav:
  - Data Depot:
    - Managing Data: managingdata.md
    - Curating &amp; Publishing Projects: curating.md
      # NOTE: External link is achieved via `js/changeNavMarkup.js`, NOT here
      # - Data Depot/Curation Office Hours: https://www.designsafe-ci.org/facilities/virtual-office-hours/
    - Recon Portal: recon.md

  - Tools and Apps:
    - Analysis Applications: analysis.md
    - Hazard Apps &amp; Utilities: tools/hazard.md
    - Jupyter: tools/jupyterhub.md
    - Visualization Applications: tools/visualization.md

  - Simulation Applications: 
    - Overview: tools/simulation/overview.md
    - ADCIRC: tools/simulation/adcirc/adcirc.md
    - ClawPack: tools/simulation/clawpack.md
    - Dakota: tools/simulation/dakota.md
    - LS-DYNA: tools/simulation/lsdyna.md
    - OpenFoam: tools/simulation/openfoam.md
    - OpenSees : tools/simulation/opensees/opensees.md

# Old navigation for OpenSees
#      - OpenSees on DesignSafe:
#        - Overview: tools/simulation/opensees/openseesOverview.md
#        - Project Size: tools/simulation/opensees/openseesProjectSize.md
#        - Decision Matrix - Applications: tools/simulation/opensees/openseesDecisionMatrixApplication.md
#        - Decision Matrix - Platforms: tools/simulation/opensees/openseesDecisionMatrixPlatform.md
#        - OpenSees at the Linux Terminal: tools/simulation/opensees/openseesRunLinux.md
#        - Resources: tools/simulation/opensees/openseesResources.md
#      - OpenSees Applications : 
#        - Overview: tools/simulation/opensees/openseesApplications.md
#        - 1. OpenSees-Express: tools/simulation/opensees/openseesExpress.md
#        - 2. OpenSeesSP: tools/simulation/opensees/openseesSP.md
#        - 3. OpenSeesMP: tools/simulation/opensees/openseesMP.md
#        - 4. OpenSeesPy: tools/simulation/opensees/openseesPy.md
#      - DesignSafe Platforms for OpenSees:
#        - Overview: tools/simulation/opensees/openseesRunning.md
#        - 1. The Interactive VM: tools/simulation/opensees/openseesRunVM.md
#        - ...1a. Specifications: tools/simulation/opensees/openseesRunVM_Specs.md
#        - 2. DesignSafe WebPortal: tools/simulation/opensees/openseesRunWebPortal.md
#        - ...2a. Form Input: tools/simulation/opensees/openseesRunWebPortal_Form.md
#        - ...2b. Specifications: tools/simulation/opensees/openseesRunWebPortal_Specs.md
#        - 3. Jupyter & OpenSeesPy: tools/simulation/opensees/openseesRunJupyterPy.md
#        - 4. Jupyter & HPC: tools/simulation/opensees/openseesRunJupyterHPC.md
#        - 5. TACC: tools/simulation/opensees/openseesRunTACC.md

  - Use Cases:
    - Overview: usecases/overview.md
    - Data Analytics: usecases/dataanalyticsusecases.md
    - GeoHazard: usecases/geohazardusecases.md
    - Seismic: usecases/seismicusecases.md
    - Wind and Storm Surge: usecases/windstormsurgeusecases.md

  - Advanced:
    - API Developer's Guide: https://tapis-cli.readthedocs.io/en/latest/
    - Cybersecurity Policy: tools/advanced/cybersecurity.md
    - DesignSafe FAQ: tools/advanced/dsfaq.md
    - HPC Allocations Policy: tools/advanced/hpcallocations.md


# ----------------------------------------------------------------
# Checking how to render Katex.
# From: https://squidfunk.github.io/mkdocs-material/reference/math/#katex-mkdocsyml
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
# ----------------------------------------------------------------

# Old navigation for unflattened use cases
#    - Data Analytics: usecases/dataanalytics-usecases.md
#      - Basic Image Browsing and Mapping: usecases/haan/usecase.md
#      - Grouping and Tagging Image Files: usecases/haan/usecase-2.md
#      - Multi-Data Set Image Analysis in Taggit: usecases/haan/usecase-3.md
#      - ML and AI: usecases/vantassel_and_zhang/usecase.md
#      - API: usecases/brandenberg-api/usecase.md
#    - GeoHazard: usecases/geohazard-usecases.md
#      - NGL Database: usecases/brandenberg-ngl/usecase.md
#      - MPM Landslide: usecases/kumar/usecase.md
#    - Wind and Storm Surge: usecases/windstormsurge-usecases.md
#      - Field Sensing Wind Events: usecases/pinelli/usecase.md
#      - Hurricane Data Integration Visualization: usecases/pinelli/2usecase.md
#      - ADCIRC Datasets: usecases/dawson/usecase2.md
#      - Large-Scale Storm Surge: usecases/dawson/usecase.md
#      - Visualizing Surge for Regional Risks: usecases/padgett/usecase.md
#      - CFD Analysis of Winds on Structures: usecases/kareem/usecase.md
#    - Seismic: usecases/seismic-usecases.md
#      - OpenSees Model Calibration: usecases/arduino/usecase.md
#      - Seismic Response of Concrete Walls: usecases/lowes/usecase.md
#      - Soil Structure Interaction: usecases/rathje/usecase.md
#      - Experimental Shake Table Testing: usecases/mosqueda/usecase.md
#      - Shake Table Data Analysis Using ML: usecases/mosqueda/erler-mosqueda.md
